plugins {
    id 'java'
    id 'groovy'
    id 'java-library'
    //id 'com.github.onslip.gradle-one-jar' version '1.0.6'
}

group 'com.EmpireLife'
version '1.0-SNAPSHOT'
description 'Testing framework for running qat-'
java.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
    flatDir {
        dirs 'lib'
    }
    mavenLocal()
    mavenCentral()
}

wrapper {
    gradleVersion = '6.9.2'
}

def cucumber_version = '7.3.4'
def selenium_version = "4.1.4"
def rest_assured_version = "4.5.0"
def driver_manager_version = '5.2.0'
def appium_version = '8.0.0'
def apache_poi_version = "5.0.0"
def jackson_version = "2.13.3"

configurations {
    cucumberRuntime {
        extendsFrom testImplementation
    }
}

dependencies {
    // Selenium
    testImplementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: selenium_version
    testImplementation group: 'org.seleniumhq.selenium', name: 'selenium-api', version: selenium_version

    // Cucumber
    testImplementation group: 'io.cucumber', name: 'cucumber-core', version: cucumber_version
    testImplementation group: 'io.cucumber', name: 'cucumber-picocontainer', version: cucumber_version
    testImplementation group: 'io.cucumber', name: 'cucumber-java', version: cucumber_version
    testImplementation group: 'io.cucumber', name: 'cucumber-junit', version: cucumber_version
    testImplementation group: 'io.cucumber', name: 'gherkin', version: '23.0.1'
    testImplementation 'com.opencsv:opencsv:5.9'
    testImplementation "com.ibm.db2:jcc:11.5.9.0"

    // ReportPortal
    testImplementation group: 'com.epam.reportportal', name: 'client-java', version: '5.1.4'
    testImplementation group: 'com.epam.reportportal', name: 'agent-java-cucumber6', version: '5.1.1'
    testImplementation group: 'com.epam.reportportal', name: 'agent-java-junit5', version: '5.1.1'
    testImplementation group: 'com.epam.reportportal', name: 'httpclient-repacked', version: '1.0.2'

    // Jackson
    testImplementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: jackson_version
    testImplementation group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: jackson_version
    testImplementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: jackson_version

    // Other
    testImplementation group: 'io.github.bonigarcia', name: 'webdrivermanager', version: driver_manager_version
    testImplementation group: 'io.rest-assured', name: 'rest-assured', version: rest_assured_version
    testImplementation group: 'org.json', name: 'json', version: '20220320'
    testImplementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'
    testImplementation group: 'org.apache.pdfbox', name: 'pdfbox', version: '2.0.26'
    testImplementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.10'
    testImplementation group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.4.13'
    testImplementation group: 'org.awaitility', name: 'awaitility', version: '4.0.3'
    testImplementation group: 'net.lightbody.bmp', name: 'browsermob-core', version: '2.1.5'
    testImplementation group: 'io.percy', name: 'percy-java-selenium', version: '0.1.4'
    testImplementation group: 'org.jsoup', name: 'jsoup', version: '1.15.1'
    testImplementation group: 'org.apache.poi', name: 'poi', version: apache_poi_version
    testImplementation group: 'org.apache.poi', name: 'poi-ooxml', version: apache_poi_version
    testImplementation group: 'io.appium', name: 'java-client', version: appium_version
    testImplementation group: 'org.jetbrains', name: 'annotations', version: '23.0.0'
    testImplementation group: 'com.jayway.jsonpath', name: 'json-path', version: '2.6.0'
    testImplementation group: 'io.netty', name: 'netty-all', version: '4.1.77.Final'

    testImplementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.17.2'
    testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.22.0'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.8.2'
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    testImplementation group: 'com.github.lambdatest', name: 'lambdatest-tunnel-binary', version: '1.0.10'
}

test {
    systemProperty "cucumber.options", System.getProperty("cucumber.options")
    systemProperty "cucumber.filter.tags", System.getProperty("cucumber.filter.tags")
    systemProperty "config.filepath", System.getProperty("config.filepath", "")
    systemProperty "config.profile", System.getProperty("config.profile", "")
    systemProperty "parallel", System.getProperty("parallel", "false")
    systemProperty "threads", System.getProperty("threads", "1")
}

task cucumber {
    delete "./build"
    dependsOn assemble, testClasses
    outputs.upToDateWhen {false}

    doLast {
        // read in the number of threads and set parallel accordingly
        int threads = Integer.parseInt(getProjectProperty("runner.threads", "1"))
        boolean parallel = false

        if (threads < 1) {
            throw new IllegalArgumentException("Illegal number of threads: " + threads)
        }
        else if (threads > 1) {
            parallel = true
        }

        // read in the profiles
        List<String> profiles

        try {
            String profilesArg = project.property("runner.profiles")

            if (profilesArg.isEmpty()) {
                throw new IllegalArgumentException("profiles is empty")
            }

            profiles = Arrays.asList(profilesArg.split(",\\s*"))
        } catch(MissingPropertyException e) {
            profiles = Arrays.asList("defaultProfile")
        }

        // if appending profile onto launch name, save current launch name so that it can be reused each launch
        boolean appendProfile = Boolean.parseBoolean(getProjectProperty("rp.launch.append.profile", "true"))
        String launchName = "default"

        if (appendProfile) {
            try {
                InputStream is = new FileInputStream("src/test/resources/reportportal.properties")
                Properties rpProps = new Properties()

                rpProps.load(is)

                if (rpProps.containsKey("rp.launch")) {
                    launchName = rpProps.getProperty("rp.launch")
                }
            } catch (Exception e) {
                logger.warn("Unable to load reportportal.properties")
                logger.debug(e.getMessage())
            }
        }

        // define our java exec variables
        String javaMain = "io.cucumber.core.cli.Main"
        FileCollection javaClasspath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
        List<String> javaArgs = ['src/test/resources/feature',
                                 '--plugin', 'com.epam.reportportal.cucumber.ScenarioReporter',
                                 '--glue', 'ca.empire',
                                 '--threads', threads,
                                 '--monochrome']

        boolean hasFailures = false

        for (String profile : profiles) {
            try {
                javaexec {
                    String currentLaunchName = launchName

                    // append profile onto launch if applicable
                    if (appendProfile) {
                        currentLaunchName = String.format("%s [profile: %s]", currentLaunchName, profile)
                    }

                    systemProperty "config.profile", profile
                    systemProperty "parallel", parallel
                    systemProperty "cucumber.options", System.getProperty("cucumber.options")
                    systemProperty "cucumber.filter.tags", System.getProperty("cucumber.filter.tags")
                    systemProperty "config.filepath", System.getProperty("config.filepath", "")
                    systemProperty "rp.launch", currentLaunchName

                    main = javaMain
                    classpath = javaClasspath
                    args = javaArgs
                }
            } catch (GradleException e) {
                hasFailures = true
                logger.info("Build for profile {} failed. This is likely the result of a failed test case.", profile)
                logger.debug(e.getMessage())
            } catch (Exception e) {
                hasFailures = true
                logger.info("An unhandled exception occured while executing tests with the profile {}", profile)
                logger.debug(e.getMessage())
            }
        }

        // check if we want to ignore test failures during the build process
        boolean ignoreFailures = Boolean.parseBoolean(getProjectProperty("runner.ignore.failures", "false"))

        if (!ignoreFailures && hasFailures) {
            throw new GradleException("One or more of the test sets experianced a failure.")
        }
    }
}

// UTIL METHODS

/**
 * Retrieves the desired Gradle Project property. If the property defined by {@code prop} is null, then we will return
 * the value stored in {@code defaultValue}.
 *
 * @param prop The key of the property that we want to retrieve.
 * @param defaultValue The default value to use in the case that there is no property with the key {@code prop}.
 * @return The property stored in {@code prop}, or {@code defaultValue} if the property does not exist.
 */
def <T> T getProjectProperty(String prop, T defaultValue) {
    T returnValue = project.findProperty(prop)

    if (returnValue == null) {
        return defaultValue
    }

    return returnValue
}